version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

sphinx:
  fail_on_warning: true
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: ./pydebiaseddta/pydebiaseddta
    - requirements: ./docs/requirements.txt

formats:
  - pdf
  - epub
