site_name: pydebiaseddta

theme:
  name: "material"

repo_url: https://github.com/rizaozcelik/pydebiaseddta/

plugins:
  - mkdocstrings

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Homepage: index.md
  - API Reference:
    - api/debiasing.md
    - api/predictors.md
    - api/guides.md
    - api/evaluation.md
    - api/sequence.md
    - api/utils.md
  