[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pydebiaseddta"
authors = [{name = "Rıza Özçelik", email = "r.ozcelik@tue.nl"}]
dynamic = ["version", "description"]
