[build-system]
requires = [
    "setuptools>=61.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "pydebiaseddta"
authors = [{name = "Rıza Özçelik", email = "riza.ozcelik@boun.edu.tr"}]
dynamic = ["version", "description"]
